version: '3'

services:
  db_postgres:
    container_name: 'db_boilerplate'
    image: 'postgres:14.4-alpine'
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./database/boilerplate:/var/lib/postgresql/data/

  init_db:
    container_name: 'init_db'
    image: 'node:18.4-alpine'
    env_file:
      - .env
    entrypoint: /bin/sh './app/scripts/db-init.sh'
    volumes: 
     - .:/app
    depends_on:
      - db_postgres
    links:
      - db_postgres