version: '3'

services:
  db_postgres:
    container_name: 'db_boilerplate'
    image: 'postgres:14.4-alpine'
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./database/boilerplate:/var/lib/postgresql/data/
      - ./scripts/db-init:/docker-entrypoint-initdb.d # all files in directory automatically executed in the alphabetical order on container creation